client_id = "a8bd6337dfd32984a749965c6d253df5"
name = "subscribe-check"
application_url = "https://newsletter-subcribe-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products,read_customers,write_customers"

[auth]
redirect_urls = [ "https://newsletter-subcribe-production.up.railway.app/api/auth" ]

[app_proxy]
url = "https://newsletter-subcribe-production.up.railway.app"
subpath = "newsletter"
prefix = "apps"
